name: ci

on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sleep 30
      - run: |
          git config --local user.name "actions@github.com"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "test commit by ci.yaml" --allow-empty
          git push origin HEAD:${{ github.head_ref }}
