name: ci

on:
  pull_request:
    branches: [main]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
      - run: git commit -m "test commit by ci.yaml" --allow-empty
